# Generated by Django 3.1.5 on 2021-02-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutAs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Опис')),
                ('photo', models.ImageField(upload_to='about_photo', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Про нас',
                'verbose_name_plural': 'Про нас',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Повна назва')),
                ('streat', models.CharField(max_length=50, verbose_name='Вулиця')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон номер 1')),
                ('phone_two', models.CharField(max_length=50, verbose_name='Телефон номер 2')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Контактні данні',
                'verbose_name_plural': 'Контактні данні',
            },
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Імя документа')),
                ('files', models.FileField(upload_to='documentation', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Документи',
                'verbose_name_plural': 'Документи',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Імя')),
                ('photo', models.ImageField(upload_to=None, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
            },
        ),
    ]
