# Generated by Django 3.1.6 on 2021-02-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210203_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('short_description', models.CharField(max_length=320, verbose_name='Деталі')),
                ('url_button', models.URLField(verbose_name='Посилання')),
                ('photo', models.ImageField(upload_to='info_photo', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Інформаційні данні',
                'verbose_name_plural': 'Інформаційні данні',
            },
        ),
    ]
