# Generated by Django 3.1.6 on 2021-02-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='short_description',
            field=models.TextField(max_length=520, verbose_name='Деталі'),
        ),
    ]
