# Generated by Django 3.1.6 on 2021-02-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210205_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='info_photo', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='info',
            name='short_description',
            field=models.TextField(blank=True, max_length=520, null=True, verbose_name='Деталі'),
        ),
        migrations.AlterField(
            model_name='info',
            name='url_button',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання'),
        ),
    ]
