# Generated by Django 3.1.6 on 2021-02-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210205_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Google карти'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон номер 1'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone_two',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон номер 2'),
        ),
    ]
