# Generated by Django 3.1.6 on 2021-02-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210205_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Google карти'),
        ),
    ]
