# Generated by Django 3.1.6 on 2021-02-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210210_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutas',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
