# Generated by Django 3.1.6 on 2021-03-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_aboutas_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Прізвище Імя Побатькові')),
                ('position', models.CharField(max_length=200, verbose_name='Посада')),
                ('photo', models.ImageField(upload_to='team_photo', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Наша команда',
                'verbose_name_plural': 'Наша команда',
            },
        ),
    ]
